name: Build revision Docker image
 
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true

jobs:
  variables-setup:
    name: Setting variables for docker build
    runs-on: ubuntu-latest
    environment: rc
    steps:        
      - name: Create variables
        id: vars
        run: |
          echo "platforms=${{ vars.BUILD_PLATFORMS }}" >> $GITHUB_OUTPUT
          echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          echo "tag=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
    outputs:
      platforms: ${{ steps.vars.outputs.platforms }}
      version: ${{ steps.vars.outputs.version }}
      tag: ${{ steps.vars.outputs.tag }}
      date: ${{ steps.vars.outputs.date }}
      
  call-docker-build:
    name: Call release candidate Docker build
    needs: variables-setup
    uses: reportportal/.github/.github/workflows/build-docker-image.yaml@main
    with:
      aws-region: ${{ vars.AWS_REGION }}
      image-tag: ${{ needs.variables-setup.outputs.tag }}
      additional-tag: 'latest'
      build-platforms: ${{ needs.variables-setup.outputs.platforms }}
      version: ${{ needs.variables-setup.outputs.version }}
      date: ${{ needs.variables-setup.outputs.date }}
    secrets: inherit
