name: Build

on:
  push:
    branches:
      - '**'
      - '!master'
    paths-ignore:
      - readme.md
      - README.md
      - CHANGELOG.md

  pull_request:
    branches:
      - master
      - develop

env:
  UI_BUILD_REACT: 'app/'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20]

    steps:
      - uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: JS Build
        env:
          NODE_OPTIONS: '--max_old_space_size=2048'

        run: |
          npm --prefix ${{ env.UI_BUILD_REACT }} ci --legacy-peer-deps
          npm --prefix ${{ env.UI_BUILD_REACT }} run lint
          npm --prefix ${{ env.UI_BUILD_REACT }} run test:coverage
          npm --prefix ${{ env.UI_BUILD_REACT }} run build

      - name: Codecov report
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
