name: Build develop Docker image

on:
  push:
    branches:
      - develop
      - 'feature/orgs'
      - 'feature/test-library'
    paths-ignore:
      - '.github/**'
      - README.md
  workflow_dispatch:

jobs:
  variables-setup:
    name: Setting variables for docker build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create variables
        id: vars
        run: |
          echo "tag=$(echo ${{ github.ref_name }}-${{ github.run_number }} | tr '/' '-')" >> $GITHUB_OUTPUT
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
    outputs:
      tag: ${{ steps.vars.outputs.tag }}
      date: ${{ steps.vars.outputs.date }}

  call-docker-build:
    name: Call develop Docker build
    needs: variables-setup
    uses: reportportal/.github/.github/workflows/build-docker-image.yaml@main
    with:
      aws-region: ${{ vars.AWS_REGION }}
      image-tag: ${{ needs.variables-setup.outputs.tag }}
      version: ${{ needs.variables-setup.outputs.tag }}
      branch: ${{ github.ref_name }}
      date: ${{ needs.variables-setup.outputs.date }}
    secrets: inherit
