name: Release

on:
  pull_request:
    types: [closed]
    branches:
      - master
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true

env:
  UI_BUILD_REACT: 'app/'
  RELEASE_DIR: 'release'
  UI_ARTIFACT_NAME: 'ui.tar.gz'
  BUILD_INFO_FILE: 'buildInfo.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get Date
        run: 'echo "BUILD_DATE=`date +%FT%T%z`" >> $GITHUB_ENV'

      - uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.0'

      - name: JS Build
        env:
          NODE_OPTIONS: '--max_old_space_size=2048'

        run: |
          npm --prefix ${{ env.UI_BUILD_REACT }} ci --legacy-peer-deps
          npm --prefix ${{ env.UI_BUILD_REACT }} run lint
          npm --prefix ${{ env.UI_BUILD_REACT }} run test:coverage
          npm --prefix ${{ env.UI_BUILD_REACT }} run build

      - name: Generate Build info
        run: |
          RELEASE_VERSION_INPUT="${{ github.event.inputs.version }}"
          if [ -z "$RELEASE_VERSION_INPUT" ]; then
          REF_NAME="${{ github.head_ref }}"

            if [[ "$REF_NAME" == rc/* ]]; then
            RELEASE_VERSION="${REF_NAME#rc/}"
            elif [[ "$REF_NAME" == hotfix/* ]]; then
            RELEASE_VERSION="${REF_NAME#hotfix/}"
            else
            echo "Error: Only 'rc/' or 'hotfix/' sub-branches can be used for releases. Found: $REF_NAME"
            exit 1
            fi
          else
          RELEASE_VERSION="$RELEASE_VERSION_INPUT"
          fi
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          echo '{"build": { "version": "'$RELEASE_VERSION'", "branch": "${{ github.ref_name }}-${{ github.sha }}", "build_date": "${{ env.BUILD_DATE }}", "name": "Service UI", "repo": "${{ github.repository }}"}}' > ./${{ env.UI_BUILD_REACT }}build/${{ env.BUILD_INFO_FILE }}

      - name: Create release directory
        run: mkdir -v ${{ github.workspace }}/${{ env.RELEASE_DIR }}

      - name: UI assets compress
        run: 'cd ${{ env.UI_BUILD_REACT }}build && tar -czvf "${{ github.workspace }}/${{ env.RELEASE_DIR }}/${{ env.UI_ARTIFACT_NAME }}" ./'

      - name: Setup git credentials
        uses: oleksiyrudenko/gha-git-credentials@v2
        with:
          name: 'reportportal.io'
          email: 'support@reportportal.io'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag release
        id: tagRelease
        run: |
          git tag -a "$RELEASE_VERSION" -m "Release $RELEASE_VERSION"
          git push --tags

      - name: Create Release
        id: createRelease
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: "Release ${{ env.RELEASE_VERSION }}"
          draft: false
          prerelease: false

      - name: Upload UI Asset
        id: upload-ui-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.createRelease.outputs.upload_url }}
          asset_path: '${{ github.workspace }}/${{ env.RELEASE_DIR }}/${{ env.UI_ARTIFACT_NAME }}'
          asset_name: ${{ env.UI_ARTIFACT_NAME }}
          asset_content_type: application/gzip
